packages:
  - pkg-a
  - pkg-b

catalogs:
  default:
    react: 18.1.0
    is-positive: kevva/is-positive#97edff6f525f192a3f83cea1944765f769ae2678
    is-negative: zkochan/is-negative#2.0.1
    is-string-custom: npm:is-string@1.0.0

  react17:
    react: ^17.0.2
    react-dom: ^17.0.2
